services:
  web:
    build: ./services/web
    command: python manage.py run --host 0.0.0.0 --port 5000
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 2233:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_flask"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

