steps:
  - uses: actions/checkout@v3

  # 1) Build & start your services in the background
  - name: Build & start services
    run: |
      docker compose build web
      docker compose up -d db web
      sleep 15           # wait for Postgres to finish init

  # 2) Now you can exec into db
  - name: Seed test data
    run: |
      docker compose exec -T db psql \
        -U hello_flask \
        -d hello_flask_dev \
        -c "CREATE TABLE test(id INT PRIMARY KEY); \
            INSERT INTO test VALUES (1),(2);"

  - name: Verify test data
    run: |
      docker compose exec -T db psql \
        -U hello_flask \
        -d hello_flask_dev \
        -t -A \
        -c "SELECT COUNT(*) FROM test;" \
      | grep -q "^2$"

  # 3) Optional: smoke-test your web app
  - name: Smoke-test web
    run: curl --fail http://localhost:2233/

  # 4) Always tear down
  - name: Tear down
    if: always()
    run: docker compose down --volumes --remove-orphans
