name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
# Install Docker Compose V2 plugin
      - name: Install Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -sSL \
            https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64 \
            -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      # Create our .env.dev so docker compose can read it
      - name: Generate .env.dev
        run: |
          cat > .env.dev <<EOF
          FLASK_APP=project/__init__.py
          FLASK_DEBUG=1
          DATABASE_URL=postgresql://hello_flask:hello_flask@db:5432/hello_flask_dev
          SQL_HOST=db
          SQL_PORT=5432
          DATABASE=postgres
          APP_FOLDER=/usr/src/app
          EOF

      # Build and start everything (db + web)
      - name: Build & bring up services
        run: |
          docker compose up -d --build

      # Wait for Postgres to be ready
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            docker compose exec -T db pg_isready -U hello_flask && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      # Seed a tiny test table
      - name: Seed test data
        run: |
          docker compose exec -T db psql \
            -U hello_flask \
            -d hello_flask_dev \
            -c "CREATE TABLE IF NOT EXISTS test (id INT PRIMARY KEY, name TEXT);
                INSERT INTO test (id,name) VALUES (1,'Alice'),(2,'Bob');"

      # Verify those two rows exist
      - name: Verify test data
        run: |
          docker compose exec -T db psql \
            -U hello_flask \
            -d hello_flask_dev \
            -t -A \
            -c "SELECT COUNT(*) FROM test;" \
          | grep -q "^2$"

      # A simple HTTP smoke-test against your Flask home page
      - name: Smoke-test web
        run: |
          curl --fail http://localhost:2233/ || (echo "Web is not responding" && exit 1)

      # Tear down (always)
      - name: Tear down
        if: always()
        run: docker compose down --volumes --remove-orphans
